### PR TITLE
Bump the dependencies manually until we set up dependabot.

### PR DESCRIPTION
**Pull request by vaikas**
Result of:
```
go get -u
go mod tidy
```

### CODE REVIEW

**Review by imjasonh — APPROVED** [review]

**Comment by imjasonh** [comment]
https://github.com/chainguard-dev/gobump/blob/f45e67e8047e2682252ad0168e87b59c08b2338c/.github/workflows/lint.yaml#L19

should be 1.23 (or `go-version-file: go.mod` or whatever)

And we probably also want to update the golangci-lint version if it matters.

**Comment by vaikas** [comment]
Locally:
```
/opt/homebrew/bin/golangci-lint run                                          ✔
cmd/gobump/root.go:34:13: unused-parameter: parameter 'cmd' seems to be unused, consider removing or renaming it as _ (revive)
	RunE: func(cmd *cobra.Command, args []string) error {
	           ^
cmd/gobump/root.go:34:33: unused-parameter: parameter 'args' seems to be unused, consider removing or renaming it as _ (revive)
	RunE: func(cmd *cobra.Command, args []string) error {
	                               ^
```

**Comment by imjasonh** [comment]
```
	RunE: func(*cobra.Command, []string) error {
```

and probably remove the comment above it, that seems useless.

(Gosh I wish GitHub made it easier to just edit your branch. ...Or that I wasn't too lazy to do that...)

**Comment by vaikas** [comment]
> ```
> 	RunE: func(*cobra.Command, []string) error {
> ```
> 
> and probably remove the comment above it, that seems useless.
> 
> (Gosh I wish GitHub made it easier to just edit your branch. ...Or that I wasn't too lazy to do that...)

Yeah, there were few other issues that I fixed.

**Review by imjasonh — APPROVED** [review]

**Review by imjasonh — APPROVED** [review]

**Pull request merged**
